import { CatalogWord } from './vocab-catalog';
import { normWord } from './norm';

// ─── A1 → A2 starter path ───────────────────────────────────────────────────────
// A gentle, ordered on-ramp for complete beginners (A1 profiles). The Vocabulary "Learn"
// tab walks this array in order, so the ORDER here is the teaching order: start with
// greetings, courtesy, question words, pronouns and numbers — the things the main
// VOCAB_CATALOG lacks and that a true beginner needs first — then move through the
// most concrete everyday themes (family, food, house, city, travel…) before the
// lighter abstract words. German (`de`) side is the learner's L1.
//
// Deduped at the bottom so an accidental repeat never produces a double flashcard.
// After the starter, app/vokabeln/page.tsx flows beginners into the rest of the
// full catalog, so they never run out.

const RAW: CatalogWord[] = [
  // ── Begrüßung & Höflichkeit ────────────────────────────────────────────────
  { de: 'hallo / tschüss (informell)', it: 'ciao' },
  { de: 'guten Morgen / guten Tag', it: 'buongiorno' },
  { de: 'guten Abend', it: 'buonasera' },
  { de: 'gute Nacht', it: 'buonanotte' },
  { de: 'auf Wiedersehen', it: 'arrivederci' },
  { de: 'bis später', it: 'a dopo' },
  { de: 'bis morgen', it: 'a domani' },
  { de: 'bis bald', it: 'a presto' },
  { de: 'willkommen', it: 'benvenuto' },
  { de: 'ja', it: 'sì' },
  { de: 'nein', it: 'no' },
  { de: 'vielleicht', it: 'forse' },
  { de: 'bitte', it: 'per favore' },
  { de: 'danke', it: 'grazie' },
  { de: 'vielen Dank', it: 'grazie mille' },
  { de: 'gern geschehen / bitte', it: 'prego' },
  { de: 'entschuldigung', it: 'scusa' },
  { de: 'Entschuldigung (höflich)', it: 'mi scusi' },
  { de: 'es tut mir leid', it: 'mi dispiace' },
  { de: 'wie geht es dir?', it: 'come stai?' },
  { de: 'gut', it: 'bene' },
  { de: 'schlecht', it: 'male' },
  { de: 'so lala', it: 'così così' },
  { de: 'sehr erfreut', it: 'piacere' },
  { de: 'wie heißt du?', it: 'come ti chiami?' },
  { de: 'ich heiße …', it: 'mi chiamo' },
  { de: 'ich verstehe nicht', it: 'non capisco' },
  { de: 'sprichst du Deutsch?', it: 'parli tedesco?' },
  { de: 'Prost!', it: 'salute!' },
  { de: 'herzlichen Glückwunsch', it: 'auguri' },
  { de: 'guten Appetit', it: 'buon appetito' },

  // ── Fragewörter ─────────────────────────────────────────────────────────────
  { de: 'was', it: 'che cosa' },
  { de: 'wer', it: 'chi' },
  { de: 'wo', it: 'dove' },
  { de: 'wann', it: 'quando' },
  { de: 'wie', it: 'come' },
  { de: 'warum / weil', it: 'perché' },
  { de: 'wie viel', it: 'quanto' },
  { de: 'welcher / welche', it: 'quale' },

  // ── Personalpronomen & Possessiv ───────────────────────────────────────────────
  { de: 'ich', it: 'io' },
  { de: 'du', it: 'tu' },
  { de: 'er', it: 'lui' },
  { de: 'sie (Einzahl)', it: 'lei' },
  { de: 'Sie (höflich)', it: 'Lei' },
  { de: 'wir', it: 'noi' },
  { de: 'ihr', it: 'voi' },
  { de: 'sie (Mehrzahl)', it: 'loro' },
  { de: 'mein', it: 'mio' },
  { de: 'dein', it: 'tuo' },
  { de: 'sein / ihr', it: 'suo' },
  { de: 'unser', it: 'nostro' },
  { de: 'euer', it: 'vostro' },

  // ── Zahlen 0–20 ──────────────────────────────────────────────────────────────
  { de: 'null', it: 'zero' },
  { de: 'eins', it: 'uno' },
  { de: 'zwei', it: 'due' },
  { de: 'drei', it: 'tre' },
  { de: 'vier', it: 'quattro' },
  { de: 'fünf', it: 'cinque' },
  { de: 'sechs', it: 'sei' },
  { de: 'sieben', it: 'sette' },
  { de: 'acht', it: 'otto' },
  { de: 'neun', it: 'nove' },
  { de: 'zehn', it: 'dieci' },
  { de: 'elf', it: 'undici' },
  { de: 'zwölf', it: 'dodici' },
  { de: 'dreizehn', it: 'tredici' },
  { de: 'vierzehn', it: 'quattordici' },
  { de: 'fünfzehn', it: 'quindici' },
  { de: 'sechzehn', it: 'sedici' },
  { de: 'siebzehn', it: 'diciassette' },
  { de: 'achtzehn', it: 'diciotto' },
  { de: 'neunzehn', it: 'diciannove' },
  { de: 'zwanzig', it: 'venti' },
  // ── Zahlen 30–100 & Ordnungszahlen ─────────────────────────────────────────────
  { de: 'einundzwanzig', it: 'ventuno' },
  { de: 'dreißig', it: 'trenta' },
  { de: 'vierzig', it: 'quaranta' },
  { de: 'fünfzig', it: 'cinquanta' },
  { de: 'sechzig', it: 'sessanta' },
  { de: 'siebzig', it: 'settanta' },
  { de: 'achtzig', it: 'ottanta' },
  { de: 'neunzig', it: 'novanta' },
  { de: 'hundert', it: 'cento' },
  { de: 'tausend', it: 'mille' },
  { de: 'erster', it: 'primo' },
  { de: 'zweiter', it: 'secondo' },
  { de: 'dritter', it: 'terzo' },
  { de: 'letzter', it: 'ultimo' },
  { de: 'die Hälfte', it: 'la metà' },
  { de: 'das Doppelte', it: 'il doppio' },

  // ── Zeit, Tage, Monate, Jahreszeiten ────────────────────────────────────────────
  { de: 'Montag', it: 'il lunedì' },
  { de: 'Dienstag', it: 'il martedì' },
  { de: 'Mittwoch', it: 'il mercoledì' },
  { de: 'Donnerstag', it: 'il giovedì' },
  { de: 'Freitag', it: 'il venerdì' },
  { de: 'Samstag', it: 'il sabato' },
  { de: 'Sonntag', it: 'la domenica' },
  { de: 'Januar', it: 'gennaio' },
  { de: 'Februar', it: 'febbraio' },
  { de: 'März', it: 'marzo' },
  { de: 'April', it: 'aprile' },
  { de: 'Mai', it: 'maggio' },
  { de: 'Juni', it: 'giugno' },
  { de: 'Juli', it: 'luglio' },
  { de: 'August', it: 'agosto' },
  { de: 'September', it: 'settembre' },
  { de: 'Oktober', it: 'ottobre' },
  { de: 'November', it: 'novembre' },
  { de: 'Dezember', it: 'dicembre' },
  { de: 'der Frühling', it: 'la primavera' },
  { de: 'der Sommer', it: "l'estate" },
  { de: 'der Herbst', it: "l'autunno" },
  { de: 'der Winter', it: "l'inverno" },
  { de: 'heute', it: 'oggi' },
  { de: 'morgen', it: 'domani' },
  { de: 'gestern', it: 'ieri' },
  { de: 'jetzt', it: 'adesso' },
  { de: 'später', it: 'più tardi' },
  { de: 'früher / vorher', it: 'prima' },
  { de: 'immer', it: 'sempre' },
  { de: 'nie / niemals', it: 'mai' },
  { de: 'manchmal', it: 'a volte' },
  { de: 'oft', it: 'spesso' },
  { de: 'bald', it: 'presto' },
  { de: 'schon / bereits', it: 'già' },
  { de: 'noch', it: 'ancora' },
  { de: 'die Sekunde', it: 'il secondo' },
  { de: 'die Minute', it: 'il minuto' },
  { de: 'die Stunde', it: "l'ora" },
  { de: 'der Tag', it: 'il giorno' },
  { de: 'die Woche', it: 'la settimana' },
  { de: 'der Monat', it: 'il mese' },
  { de: 'das Jahr', it: "l'anno" },
  { de: 'der Morgen', it: 'la mattina' },
  { de: 'der Nachmittag', it: 'il pomeriggio' },
  { de: 'der Abend', it: 'la sera' },
  { de: 'die Nacht', it: 'la notte' },
  { de: 'das Wochenende', it: 'il fine settimana' },

  // ── Farben ───────────────────────────────────────────────────────────────────
  { de: 'rot', it: 'rosso' },
  { de: 'blau', it: 'blu' },
  { de: 'hellblau', it: 'azzurro' },
  { de: 'grün', it: 'verde' },
  { de: 'gelb', it: 'giallo' },
  { de: 'schwarz', it: 'nero' },
  { de: 'weiß', it: 'bianco' },
  { de: 'grau', it: 'grigio' },
  { de: 'orange', it: 'arancione' },
  { de: 'lila / violett', it: 'viola' },
  { de: 'rosa', it: 'rosa' },
  { de: 'braun', it: 'marrone' },

  // ── Familie & Personen ─────────────────────────────────────────────────────────
  { de: 'die Mutter', it: 'la madre' },
  { de: 'der Vater', it: 'il padre' },
  { de: 'die Eltern', it: 'i genitori' },
  { de: 'die Tochter', it: 'la figlia' },
  { de: 'der Sohn', it: 'il figlio' },
  { de: 'die Kinder (eigene)', it: 'i figli' },
  { de: 'die Schwester', it: 'la sorella' },
  { de: 'der Bruder', it: 'il fratello' },
  { de: 'die Großmutter', it: 'la nonna' },
  { de: 'der Großvater', it: 'il nonno' },
  { de: 'die Tante', it: 'la zia' },
  { de: 'der Onkel', it: 'lo zio' },
  { de: 'die Cousine', it: 'la cugina' },
  { de: 'der Cousin', it: 'il cugino' },
  { de: 'die Ehefrau', it: 'la moglie' },
  { de: 'der Ehemann', it: 'il marito' },
  { de: 'der Freund / die Freundin (Partner)', it: 'il ragazzo / la ragazza' },
  { de: 'der Freund / die Freundin', it: "l'amico / l'amica" },
  { de: 'der Nachbar', it: 'il vicino' },
  { de: 'der Kollege', it: 'il collega' },
  { de: 'das Baby', it: 'il bambino piccolo' },
  { de: 'das Kind', it: 'il bambino' },
  { de: 'die Frau', it: 'la donna' },
  { de: 'der Mann', it: "l'uomo" },
  { de: 'die Person', it: 'la persona' },
  { de: 'die Leute', it: 'la gente' },
  { de: 'der Name', it: 'il nome' },

  // ── Körper ─────────────────────────────────────────────────────────────────────
  { de: 'der Kopf', it: 'la testa' },
  { de: 'die Haare', it: 'i capelli' },
  { de: 'das Gesicht', it: 'la faccia' },
  { de: 'das Auge', it: "l'occhio" },
  { de: 'die Nase', it: 'il naso' },
  { de: 'der Mund', it: 'la bocca' },
  { de: 'das Ohr', it: "l'orecchio" },
  { de: 'der Zahn', it: 'il dente' },
  { de: 'der Hals', it: 'il collo' },
  { de: 'der Arm', it: 'il braccio' },
  { de: 'die Hand', it: 'la mano' },
  { de: 'der Finger', it: 'il dito' },
  { de: 'das Bein', it: 'la gamba' },
  { de: 'der Fuß', it: 'il piede' },
  { de: 'der Bauch', it: 'la pancia' },
  { de: 'der Rücken', it: 'la schiena' },
  { de: 'das Herz', it: 'il cuore' },
  { de: 'die Haut', it: 'la pelle' },

  // ── Essen & Trinken ────────────────────────────────────────────────────────────
  { de: 'das Essen', it: 'il cibo' },
  { de: 'das Frühstück', it: 'la colazione' },
  { de: 'das Mittagessen', it: 'il pranzo' },
  { de: 'das Abendessen', it: 'la cena' },
  { de: 'das Wasser', it: "l'acqua" },
  { de: 'der Kaffee', it: 'il caffè' },
  { de: 'der Tee', it: 'il tè' },
  { de: 'der Saft', it: 'il succo' },
  { de: 'die Milch', it: 'il latte' },
  { de: 'das Bier', it: 'la birra' },
  { de: 'der Wein', it: 'il vino' },
  { de: 'das Brot', it: 'il pane' },
  { de: 'die Butter', it: 'il burro' },
  { de: 'der Käse', it: 'il formaggio' },
  { de: 'das Ei', it: "l'uovo" },
  { de: 'das Fleisch', it: 'la carne' },
  { de: 'der Fisch', it: 'il pesce' },
  { de: 'das Hühnchen', it: 'il pollo' },
  { de: 'der Schinken', it: 'il prosciutto' },
  { de: 'das Gemüse', it: 'la verdura' },
  { de: 'die Kartoffel', it: 'la patata' },
  { de: 'die Tomate', it: 'il pomodoro' },
  { de: 'die Zwiebel', it: 'la cipolla' },
  { de: 'der Salat', it: "l'insalata" },
  { de: 'der Reis', it: 'il riso' },
  { de: 'die Nudeln', it: 'la pasta' },
  { de: 'das Obst', it: 'la frutta' },
  { de: 'der Apfel', it: 'la mela' },
  { de: 'die Banane', it: 'la banana' },
  { de: 'die Orange', it: "l'arancia" },
  { de: 'die Zitrone', it: 'il limone' },
  { de: 'der Zucker', it: 'lo zucchero' },
  { de: 'das Salz', it: 'il sale' },
  { de: 'das Öl', it: "l'olio" },
  { de: 'die Suppe', it: 'la zuppa' },
  { de: 'der Kuchen', it: 'la torta' },
  { de: 'das Eis', it: 'il gelato' },
  { de: 'die Schokolade', it: 'il cioccolato' },

  // ── Zuhause, Möbel & Küche ─────────────────────────────────────────────────────
  { de: 'das Haus', it: 'la casa' },
  { de: 'die Wohnung', it: "l'appartamento" },
  { de: 'das Zimmer', it: 'la stanza' },
  { de: 'die Küche', it: 'la cucina' },
  { de: 'das Badezimmer', it: 'il bagno' },
  { de: 'das Wohnzimmer', it: 'il soggiorno' },
  { de: 'das Schlafzimmer', it: 'la camera da letto' },
  { de: 'der Garten', it: 'il giardino' },
  { de: 'die Tür', it: 'la porta' },
  { de: 'das Fenster', it: 'la finestra' },
  { de: 'die Wand', it: 'la parete' },
  { de: 'der Boden', it: 'il pavimento' },
  { de: 'der Tisch', it: 'il tavolo' },
  { de: 'der Stuhl', it: 'la sedia' },
  { de: 'das Sofa', it: 'il divano' },
  { de: 'das Bett', it: 'il letto' },
  { de: 'der Schrank', it: "l'armadio" },
  { de: 'die Lampe', it: 'la lampada' },
  { de: 'der Schlüssel', it: 'la chiave' },
  { de: 'der Teller', it: 'il piatto' },
  { de: 'das Glas', it: 'il bicchiere' },
  { de: 'die Tasse', it: 'la tazza' },
  { de: 'die Flasche', it: 'la bottiglia' },
  { de: 'das Messer', it: 'il coltello' },
  { de: 'die Gabel', it: 'la forchetta' },
  { de: 'der Löffel', it: 'il cucchiaio' },

  // ── Stadt & Orte ───────────────────────────────────────────────────────────────
  { de: 'die Stadt', it: 'la città' },
  { de: 'das Dorf', it: 'il paese' },
  { de: 'das Land (Staat)', it: 'il paese / la nazione' },
  { de: 'die Straße', it: 'la strada' },
  { de: 'der Platz', it: 'la piazza' },
  { de: 'das Geschäft / der Laden', it: 'il negozio' },
  { de: 'der Supermarkt', it: 'il supermercato' },
  { de: 'der Markt', it: 'il mercato' },
  { de: 'das Restaurant', it: 'il ristorante' },
  { de: 'die Bar / das Café', it: 'il bar' },
  { de: 'das Hotel', it: "l'albergo" },
  { de: 'der Bahnhof', it: 'la stazione' },
  { de: 'der Flughafen', it: "l'aeroporto" },
  { de: 'das Krankenhaus', it: "l'ospedale" },
  { de: 'die Apotheke', it: 'la farmacia' },
  { de: 'die Bank', it: 'la banca' },
  { de: 'die Schule', it: 'la scuola' },
  { de: 'die Kirche', it: 'la chiesa' },
  { de: 'das Museum', it: 'il museo' },
  { de: 'der Park', it: 'il parco' },
  { de: 'der Strand', it: 'la spiaggia' },
  { de: 'das Kino', it: 'il cinema' },

  // ── Reisen & Transport ──────────────────────────────────────────────────────────
  { de: 'die Reise', it: 'il viaggio' },
  { de: 'der Koffer', it: 'la valigia' },
  { de: 'der Pass', it: 'il passaporto' },
  { de: 'das Ticket / die Fahrkarte', it: 'il biglietto' },
  { de: 'die Reservierung', it: 'la prenotazione' },
  { de: 'der Tourist', it: 'il turista' },
  { de: 'das Auto', it: 'la macchina' },
  { de: 'der Bus', it: "l'autobus" },
  { de: 'die U-Bahn', it: 'la metropolitana' },
  { de: 'das Taxi', it: 'il taxi' },
  { de: 'das Flugzeug', it: "l'aereo" },
  { de: 'der Zug', it: 'il treno' },
  { de: 'das Fahrrad', it: 'la bicicletta' },
  { de: 'rechts', it: 'a destra' },
  { de: 'links', it: 'a sinistra' },
  { de: 'geradeaus', it: 'dritto' },
  { de: 'nah', it: 'vicino' },
  { de: 'weit', it: 'lontano' },

  // ── Kleidung ─────────────────────────────────────────────────────────────────────
  { de: 'die Kleidung', it: 'i vestiti' },
  { de: 'das Hemd', it: 'la camicia' },
  { de: 'die Hose', it: 'i pantaloni' },
  { de: 'das Kleid', it: 'il vestito' },
  { de: 'der Rock', it: 'la gonna' },
  { de: 'die Jacke', it: 'la giacca' },
  { de: 'der Schuh', it: 'la scarpa' },
  { de: 'die Socke', it: 'il calzino' },
  { de: 'der Hut', it: 'il cappello' },
  { de: 'die Brille', it: 'gli occhiali' },

  // ── Grundverben (regelmäßig) ─────────────────────────────────────────────────────
  { de: 'sprechen', it: 'parlare' },
  { de: 'arbeiten', it: 'lavorare' },
  { de: 'studieren / lernen', it: 'studiare' },
  { de: 'kaufen', it: 'comprare' },
  { de: 'bezahlen', it: 'pagare' },
  { de: 'anschauen', it: 'guardare' },
  { de: 'hören / zuhören', it: 'ascoltare' },
  { de: 'fragen', it: 'domandare' },
  { de: 'antworten', it: 'rispondere' },
  { de: 'anrufen / rufen', it: 'chiamare' },
  { de: 'warten', it: 'aspettare' },
  { de: 'helfen', it: 'aiutare' },
  { de: 'brauchen', it: 'avere bisogno di' },
  { de: 'tragen / bringen', it: 'portare' },
  { de: 'tanzen', it: 'ballare' },
  { de: 'singen', it: 'cantare' },
  { de: 'kochen', it: 'cucinare' },
  { de: 'reisen', it: 'viaggiare' },
  { de: 'lieben', it: 'amare' },
  { de: 'nehmen', it: 'prendere' },
  { de: 'essen', it: 'mangiare' },
  { de: 'trinken', it: 'bere' },
  { de: 'lernen', it: 'imparare' },
  { de: 'lesen', it: 'leggere' },
  { de: 'laufen / rennen', it: 'correre' },
  { de: 'verstehen', it: 'capire' },
  { de: 'leben', it: 'vivere' },
  { de: 'wohnen', it: 'abitare' },
  { de: 'schreiben', it: 'scrivere' },
  { de: 'öffnen', it: 'aprire' },
  { de: 'empfangen / bekommen', it: 'ricevere' },

  // ── Grundverben (unregelmäßig & häufig) ──────────────────────────────────────────
  { de: 'sein', it: 'essere' },
  { de: 'sich befinden / bleiben', it: 'stare' },
  { de: 'haben', it: 'avere' },
  { de: 'es gibt', it: "c'è" },
  { de: 'machen / tun', it: 'fare' },
  { de: 'gehen', it: 'andare' },
  { de: 'kommen', it: 'venire' },
  { de: 'sagen', it: 'dire' },
  { de: 'sehen', it: 'vedere' },
  { de: 'geben', it: 'dare' },
  { de: 'wissen', it: 'sapere' },
  { de: 'kennen', it: 'conoscere' },
  { de: 'können', it: 'potere' },
  { de: 'wollen', it: 'volere' },
  { de: 'müssen', it: 'dovere' },
  { de: 'denken', it: 'pensare' },
  { de: 'glauben', it: 'credere' },
  { de: 'finden', it: 'trovare' },
  { de: 'schlafen', it: 'dormire' },
  { de: 'spielen', it: 'giocare' },
  { de: 'beginnen', it: 'cominciare' },
  { de: 'beenden / aufhören', it: 'finire' },
  { de: 'heißen', it: 'chiamarsi' },
  { de: 'sich setzen', it: 'sedersi' },
  { de: 'aufstehen', it: 'alzarsi' },

  // ── Einfache Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', it: 'grande' },
  { de: 'klein', it: 'piccolo' },
  { de: 'lang', it: 'lungo' },
  { de: 'kurz', it: 'corto' },
  { de: 'hoch / groß (Person)', it: 'alto' },
  { de: 'niedrig / klein (Person)', it: 'basso' },
  { de: 'gut', it: 'buono' },
  { de: 'schlecht', it: 'cattivo' },
  { de: 'schön', it: 'bello' },
  { de: 'hässlich', it: 'brutto' },
  { de: 'neu', it: 'nuovo' },
  { de: 'alt', it: 'vecchio' },
  { de: 'jung', it: 'giovane' },
  { de: 'schnell', it: 'veloce' },
  { de: 'langsam', it: 'lento' },
  { de: 'einfach', it: 'facile' },
  { de: 'schwierig', it: 'difficile' },
  { de: 'teuer', it: 'caro' },
  { de: 'günstig / billig', it: 'economico' },
  { de: 'warm / heiß', it: 'caldo' },
  { de: 'kalt', it: 'freddo' },
  { de: 'sauber', it: 'pulito' },
  { de: 'schmutzig', it: 'sporco' },
  { de: 'voll', it: 'pieno' },
  { de: 'leer', it: 'vuoto' },
  { de: 'glücklich', it: 'felice' },
  { de: 'traurig', it: 'triste' },
  { de: 'müde', it: 'stanco' },
  { de: 'krank', it: 'malato' },
  { de: 'wichtig', it: 'importante' },
  { de: 'gleich', it: 'uguale' },
  { de: 'anders / verschieden', it: 'diverso' },
  { de: 'viel', it: 'molto / tanto' },
  { de: 'wenig', it: 'poco' },
  { de: 'mehr', it: 'più' },
  { de: 'weniger', it: 'meno' },

  // ── Natur & Wetter ──────────────────────────────────────────────────────────────
  { de: 'die Natur', it: 'la natura' },
  { de: 'der Baum', it: "l'albero" },
  { de: 'die Blume', it: 'il fiore' },
  { de: 'der Berg', it: 'la montagna' },
  { de: 'der Fluss', it: 'il fiume' },
  { de: 'das Meer', it: 'il mare' },
  { de: 'der Himmel', it: 'il cielo' },
  { de: 'die Sonne', it: 'il sole' },
  { de: 'der Mond', it: 'la luna' },
  { de: 'der Stern', it: 'la stella' },
  { de: 'die Wolke', it: 'la nuvola' },
  { de: 'der Regen', it: 'la pioggia' },
  { de: 'der Schnee', it: 'la neve' },
  { de: 'der Wind', it: 'il vento' },
  { de: 'das Feuer', it: 'il fuoco' },
  { de: 'die Erde', it: 'la terra' },

  // ── Tiere ─────────────────────────────────────────────────────────────────────────
  { de: 'das Tier', it: "l'animale" },
  { de: 'der Hund', it: 'il cane' },
  { de: 'die Katze', it: 'il gatto' },
  { de: 'das Pferd', it: 'il cavallo' },
  { de: 'der Vogel', it: "l'uccello" },
  { de: 'die Kuh', it: 'la mucca' },
  { de: 'das Schwein', it: 'il maiale' },

  // ── Schule & Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', it: 'il libro' },
  { de: 'das Heft', it: 'il quaderno' },
  { de: 'der Kugelschreiber', it: 'la penna' },
  { de: 'das Papier', it: 'la carta' },
  { de: 'der Schüler', it: 'lo studente' },
  { de: 'der Lehrer', it: "l'insegnante" },
  { de: 'die Klasse / der Unterricht', it: 'la lezione' },
  { de: 'die Prüfung', it: "l'esame" },
  { de: 'die Hausaufgaben', it: 'i compiti' },
  { de: 'die Sprache', it: 'la lingua' },
  { de: 'das Wort', it: 'la parola' },
  { de: 'der Satz', it: 'la frase' },
  { de: 'die Frage', it: 'la domanda' },
  { de: 'die Antwort', it: 'la risposta' },

  // ── Arbeit & Berufe ───────────────────────────────────────────────────────────────
  { de: 'die Arbeit', it: 'il lavoro' },
  { de: 'der Beruf', it: 'la professione' },
  { de: 'das Büro', it: "l'ufficio" },
  { de: 'der Chef / die Chefin', it: 'il capo' },
  { de: 'die Firma', it: "l'azienda" },
  { de: 'der Arzt / die Ärztin', it: 'il medico' },
  { de: 'der Lehrer (Grundschule)', it: 'il maestro' },
  { de: 'der Koch', it: 'il cuoco' },
  { de: 'der Kellner', it: 'il cameriere' },
  { de: 'der Verkäufer', it: 'il commesso' },
  { de: 'der Urlaub / die Ferien', it: 'le vacanze' },
  { de: 'der Termin', it: "l'appuntamento" },

  // ── Gesundheit ─────────────────────────────────────────────────────────────────────
  { de: 'die Gesundheit', it: 'la salute' },
  { de: 'der Schmerz', it: 'il dolore' },
  { de: 'das Fieber', it: 'la febbre' },
  { de: 'die Krankheit', it: 'la malattia' },
  { de: 'das Medikament', it: 'la medicina' },
  { de: 'die Tablette', it: 'la pastiglia' },
  { de: 'der Notfall', it: "l'emergenza" },
  { de: 'der Schlaf', it: 'il sonno' },

  // ── Technologie ─────────────────────────────────────────────────────────────────────
  { de: 'der Computer', it: 'il computer' },
  { de: 'das Handy', it: 'il cellulare' },
  { de: 'das Internet', it: 'internet' },
  { de: 'die E-Mail', it: "l'email" },
  { de: 'das Foto', it: 'la foto' },
  { de: 'das Video', it: 'il video' },
  { de: 'das Passwort', it: 'la password' },
  { de: 'der Bildschirm', it: 'lo schermo' },

  // ── Geld & Einkaufen ────────────────────────────────────────────────────────────────
  { de: 'das Geld', it: 'i soldi' },
  { de: 'der Preis', it: 'il prezzo' },
  { de: 'die Rechnung', it: 'il conto' },
  { de: 'die Kreditkarte', it: 'la carta di credito' },
  { de: 'das Bargeld', it: 'i contanti' },
  { de: 'das Angebot', it: "l'offerta" },
  { de: 'der Rabatt', it: 'lo sconto' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────────────────
  { de: 'die Liebe', it: "l'amore" },
  { de: 'die Freude', it: 'la gioia' },
  { de: 'die Angst', it: 'la paura' },
  { de: 'die Hoffnung', it: 'la speranza' },
  { de: 'freundlich', it: 'gentile' },
  { de: 'nett / sympathisch', it: 'simpatico' },
  { de: 'höflich', it: 'educato' },
  { de: 'ehrlich', it: 'onesto' },
  { de: 'mutig', it: 'coraggioso' },
  { de: 'schüchtern', it: 'timido' },
  { de: 'geduldig', it: 'paziente' },
  { de: 'lustig', it: 'divertente' },
  { de: 'intelligent', it: 'intelligente' },

  // ── Nützliche kleine Wörter (Adverbien, Präpositionen, Verbindungen) ──────────────────
  { de: 'und', it: 'e' },
  { de: 'oder', it: 'o' },
  { de: 'aber', it: 'ma' },
  { de: 'wenn / falls', it: 'se' },
  { de: 'auch', it: 'anche' },
  { de: 'auch nicht', it: 'neanche' },
  { de: 'sehr', it: 'molto' },
  { de: 'ein bisschen', it: "un po'" },
  { de: 'okay / einverstanden', it: "va bene" },
  { de: 'natürlich / klar', it: 'certo' },
  { de: 'fast', it: 'quasi' },
  { de: 'nur', it: 'solo' },
  { de: 'sogar', it: 'perfino' },
  { de: 'hier', it: 'qui' },
  { de: 'dort', it: 'lì' },
  { de: 'oben', it: 'sopra' },
  { de: 'unten', it: 'giù' },
  { de: 'drinnen', it: 'dentro' },
  { de: 'draußen', it: 'fuori' },
  { de: 'in', it: 'in' },
  { de: 'von / aus', it: 'di / da' },
  { de: 'mit', it: 'con' },
  { de: 'ohne', it: 'senza' },
  { de: 'für', it: 'per' },
  { de: 'zwischen', it: 'tra' },
  { de: 'gegen', it: 'contro' },
  { de: 'unter', it: 'sotto' },
  { de: 'über / auf', it: 'su' },
  { de: 'bis', it: 'fino a' },
  { de: 'während', it: 'durante' },
  { de: 'nach', it: 'dopo' },
  { de: 'vor (zeitlich)', it: 'prima di' },
];

// Dedupe by normalized Italian so an accidental repeat never yields a double card.
const seen = new Set<string>();
export const STARTER_VOCAB: CatalogWord[] = RAW.filter(w => {
  const k = normWord(w.it);
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});
