import { IMPORTED_VOCAB } from './vocab-imported';

export interface CatalogWord {
  de: string;
  it: string;
}

// Main vocabulary catalog, walked in order by the "Learn" tab: the hand-written
// core (common, concrete themes first), then the imported Grund- and
// Ausbauwortschatz (lib/vocab-imported.ts). Nouns carry their article so the
// gender is learned with the word; "a / b" lists accepted alternatives.
const CORE_VOCAB: CatalogWord[] = [
  // ── Häufige Verben ───────────────────────────────────────────────────────
  { de: 'sein', it: 'essere' },
  { de: 'sich befinden / bleiben', it: 'stare' },
  { de: 'haben', it: 'avere' },
  { de: 'machen / tun', it: 'fare' },
  { de: 'können', it: 'potere' },
  { de: 'sagen', it: 'dire' },
  { de: 'gehen', it: 'andare' },
  { de: 'sehen', it: 'vedere' },
  { de: 'geben', it: 'dare' },
  { de: 'wissen', it: 'sapere' },
  { de: 'wollen', it: 'volere' },
  { de: 'müssen', it: 'dovere' },
  { de: 'kommen', it: 'venire' },
  { de: 'legen / stellen', it: 'mettere' },
  { de: 'sprechen', it: 'parlare' },
  { de: 'lassen / verlassen', it: 'lasciare' },
  { de: 'folgen', it: 'seguire' },
  { de: 'ankommen', it: 'arrivare' },
  { de: 'kennen', it: 'conoscere' },
  { de: 'leben', it: 'vivere' },
  { de: 'wohnen', it: 'abitare' },
  { de: 'nehmen', it: 'prendere' },
  { de: 'denken', it: 'pensare' },
  { de: 'fragen', it: 'chiedere' },
  { de: 'finden', it: 'trovare' },
  { de: 'glauben', it: 'credere' },
  { de: 'tragen / bringen', it: 'portare' },
  { de: 'rufen / anrufen', it: 'chiamare' },
  { de: 'arbeiten', it: 'lavorare' },
  { de: 'lesen', it: 'leggere' },
  { de: 'hören', it: 'ascoltare' },
  { de: 'öffnen', it: 'aprire' },
  { de: 'schließen', it: 'chiudere' },
  { de: 'schreiben', it: 'scrivere' },
  { de: 'kaufen', it: 'comprare' },
  { de: 'essen', it: 'mangiare' },
  { de: 'trinken', it: 'bere' },
  { de: 'schlafen', it: 'dormire' },
  { de: 'spielen', it: 'giocare' },
  { de: 'beginnen', it: 'cominciare' },
  { de: 'helfen', it: 'aiutare' },
  { de: 'schauen / anschauen', it: 'guardare' },
  { de: 'brauchen', it: 'avere bisogno di' },
  { de: 'lieben', it: 'amare' },
  { de: 'rennen / laufen', it: 'correre' },
  { de: 'lernen', it: 'imparare' },
  { de: 'vergessen', it: 'dimenticare' },
  { de: 'erinnern', it: 'ricordare' },
  { de: 'bezahlen', it: 'pagare' },
  { de: 'verlieren', it: 'perdere' },
  { de: 'zeigen', it: 'mostrare' },
  { de: 'verstehen', it: 'capire' },
  { de: 'erklären', it: 'spiegare' },
  { de: 'warten', it: 'aspettare' },
  { de: 'versuchen / probieren', it: 'provare' },
  { de: 'reisen', it: 'viaggiare' },
  { de: 'tanzen', it: 'ballare' },
  { de: 'singen', it: 'cantare' },
  { de: 'kochen', it: 'cucinare' },
  { de: 'schicken / senden', it: 'mandare' },
  { de: 'antworten', it: 'rispondere' },
  { de: 'entscheiden', it: 'decidere' },
  { de: 'passieren / geschehen', it: 'succedere' },
  { de: 'bedeuten', it: 'significare' },
  { de: 'heiraten', it: 'sposarsi' },
  { de: 'sterben', it: 'morire' },
  { de: 'gewinnen', it: 'vincere' },
  { de: 'empfehlen', it: 'consigliare' },
  { de: 'erlauben', it: 'permettere' },
  { de: 'sich setzen', it: 'sedersi' },
  { de: 'aufstehen', it: 'alzarsi' },
  { de: 'waschen', it: 'lavare' },
  { de: 'malen', it: 'dipingere' },
  { de: 'bauen', it: 'costruire' },
  { de: 'zählen', it: 'contare' },
  { de: 'fehlen', it: 'mancare' },
  { de: 'gehören', it: 'appartenere' },
  { de: 'sich interessieren', it: 'interessarsi' },
  { de: 'landen', it: 'atterrare' },
  { de: 'hinaufgehen / einsteigen', it: 'salire' },
  { de: 'hinuntergehen / aussteigen', it: 'scendere' },
  { de: 'fallen', it: 'cadere' },
  { de: 'lächeln', it: 'sorridere' },
  { de: 'weinen', it: 'piangere' },
  { de: 'lachen', it: 'ridere' },
  { de: 'besuchen', it: 'visitare' },
  { de: 'telefonieren', it: 'telefonare' },
  { de: 'fahren (Auto)', it: 'guidare' },
  { de: 'fliegen', it: 'volare' },
  { de: 'schwimmen', it: 'nuotare' },
  { de: 'schieben / drücken', it: 'spingere' },
  { de: 'ziehen', it: 'tirare' },
  { de: 'buchen / reservieren', it: 'prenotare' },
  { de: 'teilen', it: 'condividere' },
  { de: 'genießen', it: 'godersi' },
  { de: 'verbessern', it: 'migliorare' },
  { de: 'ändern / wechseln', it: 'cambiare' },
  { de: 'sich treffen', it: 'incontrarsi' },

  // ── Körper ───────────────────────────────────────────────────────────────
  { de: 'der Kopf', it: 'la testa' },
  { de: 'die Haare', it: 'i capelli' },
  { de: 'das Gesicht', it: 'la faccia' },
  { de: 'das Auge', it: "l'occhio" },
  { de: 'die Nase', it: 'il naso' },
  { de: 'der Mund', it: 'la bocca' },
  { de: 'das Ohr', it: "l'orecchio" },
  { de: 'der Hals', it: 'il collo' },
  { de: 'die Schulter', it: 'la spalla' },
  { de: 'der Arm', it: 'il braccio' },
  { de: 'die Hand', it: 'la mano' },
  { de: 'der Finger', it: 'il dito' },
  { de: 'die Brust', it: 'il petto' },
  { de: 'der Bauch', it: 'la pancia' },
  { de: 'der Magen', it: 'lo stomaco' },
  { de: 'der Rücken', it: 'la schiena' },
  { de: 'das Bein', it: 'la gamba' },
  { de: 'das Knie', it: 'il ginocchio' },
  { de: 'der Fuß', it: 'il piede' },
  { de: 'die Haut', it: 'la pelle' },
  { de: 'das Blut', it: 'il sangue' },
  { de: 'das Herz', it: 'il cuore' },
  { de: 'die Lunge', it: 'il polmone' },
  { de: 'das Gehirn', it: 'il cervello' },
  { de: 'der Zahn', it: 'il dente' },
  { de: 'die Lippe', it: 'il labbro' },

  // ── Familie & Personen ───────────────────────────────────────────────────
  { de: 'die Mutter', it: 'la madre' },
  { de: 'der Vater', it: 'il padre' },
  { de: 'die Eltern', it: 'i genitori' },
  { de: 'die Tochter', it: 'la figlia' },
  { de: 'der Sohn', it: 'il figlio' },
  { de: 'die Kinder (eigene)', it: 'i figli' },
  { de: 'die Schwester', it: 'la sorella' },
  { de: 'der Bruder', it: 'il fratello' },
  { de: 'die Geschwister', it: 'i fratelli' },
  { de: 'die Großmutter', it: 'la nonna' },
  { de: 'der Großvater', it: 'il nonno' },
  { de: 'die Tante', it: 'la zia' },
  { de: 'der Onkel', it: 'lo zio' },
  { de: 'die Cousine', it: 'la cugina' },
  { de: 'der Cousin', it: 'il cugino' },
  { de: 'die Nichte / die Enkelin', it: 'la nipote' },
  { de: 'der Neffe / der Enkel', it: 'il nipote' },
  { de: 'die Ehefrau', it: 'la moglie' },
  { de: 'der Ehemann', it: 'il marito' },
  { de: 'der Freund / die Freundin (Partner)', it: 'il ragazzo / la ragazza' },
  { de: 'der Freund / die Freundin', it: "l'amico / l'amica" },
  { de: 'der Nachbar', it: 'il vicino di casa' },
  { de: 'der Kollege', it: 'il collega' },
  { de: 'das Baby', it: 'il neonato' },
  { de: 'das Kind', it: 'il bambino' },
  { de: 'der Jugendliche', it: 'il ragazzo' },
  { de: 'der Erwachsene', it: "l'adulto" },
  { de: 'die Person', it: 'la persona' },
  { de: 'der Mensch', it: "l'essere umano" },

  // ── Essen & Trinken ──────────────────────────────────────────────────────
  { de: 'das Brot', it: 'il pane' },
  { de: 'die Butter', it: 'il burro' },
  { de: 'der Käse', it: 'il formaggio' },
  { de: 'das Ei', it: "l'uovo" },
  { de: 'die Milch', it: 'il latte' },
  { de: 'der Joghurt', it: "lo yogurt" },
  { de: 'das Fleisch', it: 'la carne' },
  { de: 'der Fisch', it: 'il pesce' },
  { de: 'das Hühnchen', it: 'il pollo' },
  { de: 'das Schweinefleisch', it: 'il maiale' },
  { de: 'das Rindfleisch', it: 'il manzo' },
  { de: 'der Schinken', it: 'il prosciutto' },
  { de: 'die Wurst', it: 'la salsiccia' },
  { de: 'das Gemüse', it: 'la verdura' },
  { de: 'die Kartoffel', it: 'la patata' },
  { de: 'die Tomate', it: 'il pomodoro' },
  { de: 'die Zwiebel', it: 'la cipolla' },
  { de: 'der Knoblauch', it: "l'aglio" },
  { de: 'die Karotte', it: 'la carota' },
  { de: 'der Salat', it: "l'insalata" },
  { de: 'die Bohne', it: 'il fagiolo' },
  { de: 'der Reis', it: 'il riso' },
  { de: 'die Nudeln', it: 'la pasta' },
  { de: 'das Obst', it: 'la frutta' },
  { de: 'der Apfel', it: 'la mela' },
  { de: 'die Birne', it: 'la pera' },
  { de: 'die Banane', it: 'la banana' },
  { de: 'die Orange', it: "l'arancia" },
  { de: 'die Erdbeere', it: 'la fragola' },
  { de: 'die Traube', it: "l'uva" },
  { de: 'die Zitrone', it: 'il limone' },
  { de: 'die Wassermelone', it: "l'anguria" },
  { de: 'das Wasser', it: "l'acqua" },
  { de: 'der Kaffee', it: 'il caffè' },
  { de: 'der Tee', it: 'il tè' },
  { de: 'der Saft', it: 'il succo' },
  { de: 'das Bier', it: 'la birra' },
  { de: 'der Wein', it: 'il vino' },
  { de: 'der Zucker', it: 'lo zucchero' },
  { de: 'das Salz', it: 'il sale' },
  { de: 'der Pfeffer', it: 'il pepe' },
  { de: 'das Öl', it: "l'olio" },
  { de: 'die Soße', it: 'la salsa' },
  { de: 'die Suppe', it: 'la zuppa' },
  { de: 'der Kuchen', it: 'la torta' },
  { de: 'das Eis', it: 'il gelato' },
  { de: 'die Schokolade', it: 'il cioccolato' },
  { de: 'das Frühstück', it: 'la colazione' },
  { de: 'das Mittagessen', it: 'il pranzo' },
  { de: 'das Abendessen', it: 'la cena' },

  // ── Zuhause & Möbel ──────────────────────────────────────────────────────
  { de: 'das Haus', it: 'la casa' },
  { de: 'die Wohnung', it: "l'appartamento" },
  { de: 'das Zimmer', it: 'la stanza' },
  { de: 'die Küche', it: 'la cucina' },
  { de: 'das Badezimmer', it: 'il bagno' },
  { de: 'das Wohnzimmer', it: 'il soggiorno' },
  { de: 'das Schlafzimmer', it: 'la camera da letto' },
  { de: 'die Tür', it: 'la porta' },
  { de: 'das Fenster', it: 'la finestra' },
  { de: 'die Treppe', it: 'la scala' },
  { de: 'der Tisch', it: 'il tavolo' },
  { de: 'der Stuhl', it: 'la sedia' },
  { de: 'das Sofa', it: 'il divano' },
  { de: 'das Bett', it: 'il letto' },
  { de: 'der Schrank', it: "l'armadio" },
  { de: 'das Regal', it: 'lo scaffale' },
  { de: 'die Lampe', it: 'la lampada' },
  { de: 'der Spiegel', it: 'lo specchio' },
  { de: 'der Teppich', it: 'il tappeto' },
  { de: 'der Vorhang', it: 'la tenda' },
  { de: 'der Kühlschrank', it: 'il frigorifero' },
  { de: 'der Herd', it: 'il fornello' },
  { de: 'die Waschmaschine', it: 'la lavatrice' },
  { de: 'der Staubsauger', it: "l'aspirapolvere" },
  { de: 'der Schlüssel', it: 'la chiave' },

  // ── Farben ───────────────────────────────────────────────────────────────
  { de: 'rot', it: 'rosso' },
  { de: 'blau', it: 'blu' },
  { de: 'hellblau', it: 'azzurro' },
  { de: 'grün', it: 'verde' },
  { de: 'gelb', it: 'giallo' },
  { de: 'schwarz', it: 'nero' },
  { de: 'weiß', it: 'bianco' },
  { de: 'grau', it: 'grigio' },
  { de: 'orange', it: 'arancione' },
  { de: 'lila / violett', it: 'viola' },
  { de: 'rosa', it: 'rosa' },
  { de: 'braun', it: 'marrone' },
  { de: 'beige', it: 'beige' },
  { de: 'golden', it: 'dorato' },
  { de: 'silbern', it: 'argentato' },

  // ── Zeit ─────────────────────────────────────────────────────────────────
  { de: 'die Sekunde', it: 'il secondo' },
  { de: 'die Minute', it: 'il minuto' },
  { de: 'die Stunde', it: "l'ora" },
  { de: 'der Tag', it: 'il giorno' },
  { de: 'die Woche', it: 'la settimana' },
  { de: 'der Monat', it: 'il mese' },
  { de: 'das Jahr', it: "l'anno" },
  { de: 'heute', it: 'oggi' },
  { de: 'gestern', it: 'ieri' },
  { de: 'morgen', it: 'domani' },
  { de: 'jetzt', it: 'adesso / ora' },
  { de: 'später', it: 'più tardi' },
  { de: 'früher / vorher', it: 'prima' },
  { de: 'immer', it: 'sempre' },
  { de: 'nie / niemals', it: 'mai' },
  { de: 'manchmal', it: 'a volte' },
  { de: 'oft', it: 'spesso' },
  { de: 'selten', it: 'raramente' },
  { de: 'bald', it: 'presto' },
  { de: 'schon / bereits', it: 'già' },
  { de: 'noch', it: 'ancora' },
  { de: 'der Morgen', it: 'la mattina' },
  { de: 'der Nachmittag', it: 'il pomeriggio' },
  { de: 'der Abend', it: 'la sera' },
  { de: 'die Nacht', it: 'la notte' },
  { de: 'das Wochenende', it: 'il fine settimana' },
  { de: 'Montag', it: 'il lunedì' },
  { de: 'Dienstag', it: 'il martedì' },
  { de: 'Mittwoch', it: 'il mercoledì' },
  { de: 'Donnerstag', it: 'il giovedì' },
  { de: 'Freitag', it: 'il venerdì' },
  { de: 'Samstag', it: 'il sabato' },
  { de: 'Sonntag', it: 'la domenica' },
  { de: 'Januar', it: 'gennaio' },
  { de: 'Februar', it: 'febbraio' },
  { de: 'März', it: 'marzo' },
  { de: 'April', it: 'aprile' },
  { de: 'Mai', it: 'maggio' },
  { de: 'Juni', it: 'giugno' },
  { de: 'Juli', it: 'luglio' },
  { de: 'August', it: 'agosto' },
  { de: 'September', it: 'settembre' },
  { de: 'Oktober', it: 'ottobre' },
  { de: 'November', it: 'novembre' },
  { de: 'Dezember', it: 'dicembre' },

  // ── Natur & Wetter ───────────────────────────────────────────────────────
  { de: 'die Natur', it: 'la natura' },
  { de: 'der Baum', it: "l'albero" },
  { de: 'die Blume', it: 'il fiore' },
  { de: 'das Gras', it: "l'erba" },
  { de: 'der Wald', it: 'il bosco' },
  { de: 'der Berg', it: 'la montagna' },
  { de: 'das Tal', it: 'la valle' },
  { de: 'der Fluss', it: 'il fiume' },
  { de: 'der See', it: 'il lago' },
  { de: 'das Meer', it: 'il mare' },
  { de: 'der Strand', it: 'la spiaggia' },
  { de: 'die Insel', it: "l'isola" },
  { de: 'die Küste', it: 'la costa' },
  { de: 'die Wüste', it: 'il deserto' },
  { de: 'der Himmel', it: 'il cielo' },
  { de: 'die Sonne', it: 'il sole' },
  { de: 'der Mond', it: 'la luna' },
  { de: 'der Stern', it: 'la stella' },
  { de: 'die Wolke', it: 'la nuvola' },
  { de: 'der Regen', it: 'la pioggia' },
  { de: 'der Schnee', it: 'la neve' },
  { de: 'der Wind', it: 'il vento' },
  { de: 'das Gewitter', it: 'il temporale' },
  { de: 'der Blitz', it: 'il fulmine' },
  { de: 'der Nebel', it: 'la nebbia' },
  { de: 'der Frühling', it: 'la primavera' },
  { de: 'der Sommer', it: "l'estate" },
  { de: 'der Herbst', it: "l'autunno" },
  { de: 'der Winter', it: "l'inverno" },
  { de: 'die Temperatur', it: 'la temperatura' },

  // ── Stadt & Orte ─────────────────────────────────────────────────────────
  { de: 'die Stadt', it: 'la città' },
  { de: 'das Dorf', it: 'il paese' },
  { de: 'das Land (Staat)', it: 'la nazione' },
  { de: 'die Straße', it: 'la strada' },
  { de: 'der Platz', it: 'la piazza' },
  { de: 'die Brücke', it: 'il ponte' },
  { de: 'das Geschäft / der Laden', it: 'il negozio' },
  { de: 'der Supermarkt', it: 'il supermercato' },
  { de: 'der Markt', it: 'il mercato' },
  { de: 'der Bahnhof', it: 'la stazione' },
  { de: 'der Flughafen', it: "l'aeroporto" },
  { de: 'das Hotel', it: "l'albergo" },
  { de: 'das Restaurant', it: 'il ristorante' },
  { de: 'die Bar / das Café', it: 'il bar' },
  { de: 'die Kirche', it: 'la chiesa' },
  { de: 'das Museum', it: 'il museo' },
  { de: 'das Krankenhaus', it: "l'ospedale" },
  { de: 'die Apotheke', it: 'la farmacia' },
  { de: 'die Bank', it: 'la banca' },
  { de: 'das Büro', it: "l'ufficio" },
  { de: 'die Schule', it: 'la scuola' },
  { de: 'die Universität', it: "l'università" },
  { de: 'die Bibliothek', it: 'la biblioteca' },
  { de: 'das Theater', it: 'il teatro' },
  { de: 'das Kino', it: 'il cinema' },
  { de: 'der Park', it: 'il parco' },
  { de: 'der Friedhof', it: 'il cimitero' },
  { de: 'das Rathaus', it: 'il municipio' },
  { de: 'die Post', it: "l'ufficio postale" },
  { de: 'die Polizei', it: 'la polizia' },

  // ── Arbeit & Berufe ──────────────────────────────────────────────────────
  { de: 'die Arbeit', it: 'il lavoro' },
  { de: 'der Beruf', it: 'la professione' },
  { de: 'das Gehalt', it: 'lo stipendio' },
  { de: 'der Chef / die Chefin', it: 'il capo' },
  { de: 'der Mitarbeiter', it: "l'impiegato" },
  { de: 'die Firma', it: "l'azienda" },
  { de: 'die Besprechung', it: 'la riunione' },
  { de: 'das Projekt', it: 'il progetto' },
  { de: 'der Termin', it: "l'appuntamento" },
  { de: 'die Pause', it: 'la pausa' },
  { de: 'der Urlaub', it: 'le ferie' },
  { de: 'der Vertrag', it: 'il contratto' },
  { de: 'der Arzt / die Ärztin', it: 'il medico' },
  { de: 'der Anwalt', it: "l'avvocato" },
  { de: 'der Ingenieur', it: "l'ingegnere" },
  { de: 'der Lehrer', it: "l'insegnante" },
  { de: 'der Koch', it: 'il cuoco' },
  { de: 'der Fahrer', it: "l'autista" },
  { de: 'der Polizist', it: 'il poliziotto' },
  { de: 'der Architekt', it: "l'architetto" },
  { de: 'der Programmierer', it: 'il programmatore' },
  { de: 'der Journalist', it: 'il giornalista' },
  { de: 'der Verkäufer', it: 'il commesso' },
  { de: 'der Kellner', it: 'il cameriere' },
  { de: 'die Sekretärin', it: 'la segretaria' },

  // ── Reisen & Transport ───────────────────────────────────────────────────
  { de: 'die Reise', it: 'il viaggio' },
  { de: 'das Gepäck', it: 'il bagaglio' },
  { de: 'der Koffer', it: 'la valigia' },
  { de: 'der Pass', it: 'il passaporto' },
  { de: 'das Visum', it: 'il visto' },
  { de: 'die Unterkunft', it: "l'alloggio" },
  { de: 'die Reservierung', it: 'la prenotazione' },
  { de: 'das Ticket / die Fahrkarte', it: 'il biglietto' },
  { de: 'der Ausflug', it: "la gita" },
  { de: 'die Sehenswürdigkeit', it: "l'attrazione" },
  { de: 'der Stadtplan', it: 'la cartina' },
  { de: 'der Tourist', it: 'il turista' },
  { de: 'das Auto', it: 'la macchina' },
  { de: 'der Bus', it: "l'autobus" },
  { de: 'die U-Bahn', it: 'la metropolitana' },
  { de: 'das Taxi', it: 'il taxi' },
  { de: 'das Flugzeug', it: "l'aereo" },
  { de: 'der Zug', it: 'il treno' },
  { de: 'das Schiff', it: 'la nave' },
  { de: 'das Fahrrad', it: 'la bicicletta' },

  // ── Gesundheit ───────────────────────────────────────────────────────────
  { de: 'die Gesundheit', it: 'la salute' },
  { de: 'der Patient', it: 'il paziente' },
  { de: 'das Medikament', it: 'la medicina' },
  { de: 'die Tablette', it: 'la pastiglia' },
  { de: 'die Krankheit', it: 'la malattia' },
  { de: 'der Schmerz', it: 'il dolore' },
  { de: 'das Fieber', it: 'la febbre' },
  { de: 'der Husten', it: 'la tosse' },
  { de: 'der Schnupfen / die Erkältung', it: 'il raffreddore' },
  { de: 'die Grippe', it: "l'influenza" },
  { de: 'die Allergie', it: "l'allergia" },
  { de: 'die Operation', it: "l'operazione" },
  { de: 'die Untersuchung', it: 'la visita medica' },
  { de: 'der Verband', it: 'la benda' },
  { de: 'die Verletzung', it: 'la ferita' },
  { de: 'der Notfall', it: "l'emergenza" },
  { de: 'das Rezept (Arzt)', it: 'la ricetta' },
  { de: 'die Spritze', it: "l'iniezione" },

  // ── Technologie ──────────────────────────────────────────────────────────
  { de: 'der Computer', it: 'il computer' },
  { de: 'das Handy', it: 'il cellulare' },
  { de: 'das Internet', it: 'internet' },
  { de: 'die Webseite', it: 'il sito web' },
  { de: 'die App', it: "l'app" },
  { de: 'die E-Mail', it: "l'email" },
  { de: 'der Drucker', it: 'la stampante' },
  { de: 'der Bildschirm', it: 'lo schermo' },
  { de: 'die Tastatur', it: 'la tastiera' },
  { de: 'die Kamera', it: 'la macchina fotografica' },
  { de: 'das Foto', it: 'la foto' },
  { de: 'das Video', it: 'il video' },
  { de: 'das Passwort', it: 'la password' },
  { de: 'die Datei', it: 'il file' },
  { de: 'das Netzwerk', it: 'la rete' },

  // ── Geld & Einkaufen ─────────────────────────────────────────────────────
  { de: 'das Geld', it: 'i soldi' },
  { de: 'der Preis', it: 'il prezzo' },
  { de: 'teuer', it: 'caro' },
  { de: 'günstig / billig', it: 'economico' },
  { de: 'die Rechnung (Restaurant)', it: 'il conto' },
  { de: 'die Rechnung (Firma)', it: 'la fattura' },
  { de: 'die Quittung / der Kassenbon', it: 'lo scontrino' },
  { de: 'die Kreditkarte', it: 'la carta di credito' },
  { de: 'das Bargeld', it: 'i contanti' },
  { de: 'der Rabatt', it: 'lo sconto' },
  { de: 'das Angebot', it: "l'offerta" },
  { de: 'die Kasse', it: 'la cassa' },
  { de: 'das Kaufhaus', it: 'il grande magazzino' },
  { de: 'die Steuer', it: 'la tassa' },
  { de: 'das Budget', it: 'il budget' },

  // ── Kleidung ─────────────────────────────────────────────────────────────
  { de: 'die Kleidung', it: 'i vestiti' },
  { de: 'das Hemd', it: 'la camicia' },
  { de: 'die Hose', it: 'i pantaloni' },
  { de: 'das Kleid', it: 'il vestito' },
  { de: 'der Rock', it: 'la gonna' },
  { de: 'der Pullover', it: 'il maglione' },
  { de: 'die Jacke', it: 'la giacca' },
  { de: 'der Mantel', it: 'il cappotto' },
  { de: 'der Schuh', it: 'la scarpa' },
  { de: 'der Stiefel', it: 'lo stivale' },
  { de: 'die Socke', it: 'il calzino' },
  { de: 'die Unterwäsche', it: 'la biancheria intima' },
  { de: 'der Hut', it: 'il cappello' },
  { de: 'die Mütze', it: 'il berretto' },
  { de: 'der Schal', it: 'la sciarpa' },
  { de: 'die Handschuhe', it: 'i guanti' },
  { de: 'der Gürtel', it: 'la cintura' },
  { de: 'die Brille', it: 'gli occhiali' },

  // ── Tiere ────────────────────────────────────────────────────────────────
  { de: 'das Tier', it: "l'animale" },
  { de: 'der Hund', it: 'il cane' },
  { de: 'die Katze', it: 'il gatto' },
  { de: 'das Pferd', it: 'il cavallo' },
  { de: 'die Kuh', it: 'la mucca' },
  { de: 'das Schwein', it: 'il maiale' },
  { de: 'das Schaf', it: 'la pecora' },
  { de: 'der Vogel', it: "l'uccello" },
  { de: 'die Schlange', it: 'il serpente' },
  { de: 'der Löwe', it: 'il leone' },
  { de: 'der Tiger', it: 'la tigre' },
  { de: 'der Bär', it: "l'orso" },
  { de: 'der Wolf', it: 'il lupo' },
  { de: 'der Elefant', it: "l'elefante" },
  { de: 'der Affe', it: 'la scimmia' },
  { de: 'die Maus', it: 'il topo' },
  { de: 'das Insekt', it: "l'insetto" },

  // ── Adjektive ────────────────────────────────────────────────────────────
  { de: 'groß', it: 'grande' },
  { de: 'klein', it: 'piccolo' },
  { de: 'lang', it: 'lungo' },
  { de: 'kurz', it: 'corto' },
  { de: 'breit', it: 'largo' },
  { de: 'schmal / eng', it: 'stretto' },
  { de: 'hoch', it: 'alto' },
  { de: 'niedrig / tief', it: 'basso' },
  { de: 'schwer', it: 'pesante' },
  { de: 'leicht (Gewicht)', it: 'leggero' },
  { de: 'schnell', it: 'veloce' },
  { de: 'langsam', it: 'lento' },
  { de: 'neu', it: 'nuovo' },
  { de: 'alt', it: 'vecchio' },
  { de: 'jung', it: 'giovane' },
  { de: 'modern', it: 'moderno' },
  { de: 'gut', it: 'buono' },
  { de: 'schlecht', it: 'cattivo' },
  { de: 'schön', it: 'bello' },
  { de: 'hässlich', it: 'brutto' },
  { de: 'sauber', it: 'pulito' },
  { de: 'schmutzig', it: 'sporco' },
  { de: 'voll', it: 'pieno' },
  { de: 'leer', it: 'vuoto' },
  { de: 'warm / heiß', it: 'caldo' },
  { de: 'kalt', it: 'freddo' },
  { de: 'kühl / frisch', it: 'fresco' },
  { de: 'trocken', it: 'secco' },
  { de: 'nass', it: 'bagnato' },
  { de: 'laut', it: 'rumoroso' },
  { de: 'leise / still', it: 'silenzioso' },
  { de: 'hell', it: 'chiaro' },
  { de: 'dunkel', it: 'scuro' },
  { de: 'stark', it: 'forte' },
  { de: 'schwach', it: 'debole' },
  { de: 'reich', it: 'ricco' },
  { de: 'arm', it: 'povero' },
  { de: 'glücklich', it: 'felice' },
  { de: 'traurig', it: 'triste' },
  { de: 'müde', it: 'stanco' },
  { de: 'krank', it: 'malato' },
  { de: 'gesund', it: 'sano' },
  { de: 'interessant', it: 'interessante' },
  { de: 'langweilig', it: 'noioso' },
  { de: 'wichtig', it: 'importante' },
  { de: 'nötig', it: 'necessario' },
  { de: 'möglich', it: 'possibile' },
  { de: 'unmöglich', it: 'impossibile' },
  { de: 'sicher', it: 'sicuro' },
  { de: 'gefährlich', it: 'pericoloso' },
  { de: 'einfach', it: 'semplice' },
  { de: 'kompliziert', it: 'complicato' },
  { de: 'berühmt', it: 'famoso' },
  { de: 'allgemein', it: 'generale' },
  { de: 'besonders', it: 'speciale' },
  { de: 'normal', it: 'normale' },
  { de: 'anders / verschieden', it: 'diverso' },
  { de: 'ähnlich', it: 'simile' },
  { de: 'gleich', it: 'uguale' },
  { de: 'typisch', it: 'tipico' },

  // ── Emotionen & Charakter ────────────────────────────────────────────────
  { de: 'die Freude', it: 'la gioia' },
  { de: 'die Traurigkeit', it: 'la tristezza' },
  { de: 'die Angst', it: 'la paura' },
  { de: 'die Wut', it: 'la rabbia' },
  { de: 'die Überraschung', it: 'la sorpresa' },
  { de: 'die Liebe', it: "l'amore" },
  { de: 'der Hass', it: "l'odio" },
  { de: 'die Hoffnung', it: 'la speranza' },
  { de: 'die Enttäuschung', it: 'la delusione' },
  { de: 'stolz', it: 'orgoglioso' },
  { de: 'neidisch', it: 'invidioso' },
  { de: 'dankbar', it: 'grato' },
  { de: 'freundlich', it: 'gentile' },
  { de: 'höflich', it: 'educato' },
  { de: 'unhöflich', it: 'maleducato' },
  { de: 'ehrlich', it: 'onesto' },
  { de: 'treu', it: 'fedele' },
  { de: 'mutig', it: 'coraggioso' },
  { de: 'schüchtern', it: 'timido' },
  { de: 'neugierig', it: 'curioso' },
  { de: 'geduldig', it: 'paziente' },
  { de: 'ungeduldig', it: 'impaziente' },
  { de: 'selbstbewusst', it: 'sicuro di sé' },
  { de: 'großzügig', it: 'generoso' },
  { de: 'geizig', it: 'tirchio' },
  { de: 'verantwortungsbewusst', it: 'responsabile' },
  { de: 'kreativ', it: 'creativo' },
  { de: 'intelligent', it: 'intelligente' },
  { de: 'lustig', it: 'divertente' },
  { de: 'ernst', it: 'serio' },

  // ── Bildung ──────────────────────────────────────────────────────────────
  { de: 'das Buch', it: 'il libro' },
  { de: 'das Heft', it: 'il quaderno' },
  { de: 'der Kugelschreiber', it: 'la penna' },
  { de: 'der Bleistift', it: 'la matita' },
  { de: 'das Papier', it: 'la carta' },
  { de: 'der Schüler', it: 'lo studente' },
  { de: 'die Prüfung', it: "l'esame" },
  { de: 'die Note', it: 'il voto' },
  { de: 'die Hausaufgaben', it: 'i compiti' },
  { de: 'die Klasse', it: 'la classe' },
  { de: 'das Schulfach', it: 'la materia' },
  { de: 'die Sprache', it: 'la lingua' },
  { de: 'das Wort', it: 'la parola' },
  { de: 'der Satz', it: 'la frase' },
  { de: 'der Fehler', it: "l'errore" },
  { de: 'das Zeugnis', it: 'la pagella' },

  // ── Musik & Freizeit ─────────────────────────────────────────────────────
  { de: 'die Musik', it: 'la musica' },
  { de: 'das Lied', it: 'la canzone' },
  { de: 'das Konzert', it: 'il concerto' },
  { de: 'der Film', it: 'il film' },
  { de: 'der Sport', it: 'lo sport' },
  { de: 'das Spiel', it: 'il gioco' },
  { de: 'das Hobby', it: "l'hobby" },
  { de: 'die Freizeit', it: 'il tempo libero' },
  { de: 'die Ferien', it: 'le vacanze' },
  { de: 'das Fest / die Party', it: 'la festa' },
  { de: 'der Geburtstag', it: 'il compleanno' },
  { de: 'das Geschenk', it: 'il regalo' },
  { de: 'der Fußball', it: 'il calcio' },
  { de: 'das Tennis', it: 'il tennis' },

  // ── Abstrakte Begriffe ───────────────────────────────────────────────────
  { de: 'die Idee', it: "l'idea" },
  { de: 'das Problem', it: 'il problema' },
  { de: 'die Lösung', it: 'la soluzione' },
  { de: 'der Grund', it: 'il motivo' },
  { de: 'das Ergebnis', it: 'il risultato' },
  { de: 'die Möglichkeit', it: 'la possibilità' },
  { de: 'der Unterschied', it: 'la differenza' },
  { de: 'die Wahl', it: 'la scelta' },
  { de: 'der Erfolg', it: 'il successo' },
  { de: 'die Erfahrung', it: "l'esperienza" },
  { de: 'das Wissen', it: 'la conoscenza' },
  { de: 'die Meinung', it: "l'opinione" },
  { de: 'die Frage', it: 'la domanda' },
  { de: 'die Antwort', it: 'la risposta' },
  { de: 'die Hilfe', it: "l'aiuto" },
  { de: 'der Rat', it: 'il consiglio' },
  { de: 'die Information', it: "l'informazione" },
  { de: 'die Nachricht', it: 'il messaggio' },
  { de: 'das Gespräch', it: 'la conversazione' },
  { de: 'die Entscheidung', it: 'la decisione' },
  { de: 'die Veränderung', it: 'il cambiamento' },
  { de: 'der Plan', it: 'il piano' },
  { de: 'das Ziel', it: "l'obiettivo" },
  { de: 'die Aufgabe', it: 'il compito' },
  { de: 'die Verantwortung', it: 'la responsabilità' },
  { de: 'die Freiheit', it: 'la libertà' },
  { de: 'die Wahrheit', it: 'la verità' },
  { de: 'die Lüge', it: 'la bugia' },
  { de: 'das Vertrauen', it: 'la fiducia' },
  { de: 'der Respekt', it: 'il rispetto' },
  { de: 'die Gesellschaft', it: 'la società' },
  { de: 'die Kultur', it: 'la cultura' },
  { de: 'die Geschichte', it: 'la storia' },
  { de: 'die Politik', it: 'la politica' },
  { de: 'die Wirtschaft', it: "l'economia" },
  { de: 'die Umwelt', it: "l'ambiente" },
  { de: 'die Energie', it: "l'energia" },
  { de: 'das Recht', it: 'il diritto' },
  { de: 'die Pflicht', it: 'il dovere' },
  { de: 'der Vorteil', it: 'il vantaggio' },
  { de: 'der Nachteil', it: 'lo svantaggio' },
  { de: 'der Fortschritt', it: 'il progresso' },
  { de: 'die Entwicklung', it: 'lo sviluppo' },
  { de: 'die Situation', it: 'la situazione' },
  { de: 'das Thema', it: "l'argomento" },
  { de: 'der Bereich', it: "l'ambito / il settore" },
  { de: 'das Beispiel', it: "l'esempio" },
  { de: 'der Teil', it: 'la parte' },
  { de: 'die Gruppe', it: 'il gruppo' },
  { de: 'die Mehrheit', it: 'la maggioranza' },
  { de: 'die Minderheit', it: 'la minoranza' },
];

export const VOCAB_CATALOG: CatalogWord[] = [...CORE_VOCAB, ...IMPORTED_VOCAB];
